<?php
$this->headScript()->prependFile($this->basePath() . '/js/user.js');
$appHelper = $this->ApplicationHelper();
$titleName = $appHelper->getHeadTitle('Omolink\User\ListView');
$this->headTitle($titleName);

?>
<div class="bs-callout bs-callout-info">
    <h4 id="title-user" class="title-text-bold"><?php echo $this->escapeHtml($titleName); ?></h4>
</div>

<div class="alert alert-info" role="alert" <?= isset($this->successMessage) ? '' : 'style="display:none"' ?>>
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span id="info-message"><?= isset($this->successMessage) ? $this->translate($this->successMessage) : '' ?></span>
</div>
<div class="alert alert-danger" role="alert" <?= isset($this->errorMessage) ? '' : 'style="display:none"' ?>>
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span id="error-message"><?= isset($this->errorMessage) ? $this->translate($this->errorMessage) : '' ?></span>
</div>

<div id="deleteComfirmPopup" class="overlay-content" style="width:250px;height:120px">
    <div class="popup-title"><?php echo $this->escapeHtml($titleName); ?></div>
    <div class="popup-content">選択されたユーザーを削除しますか？</div>
    <div class="popup-buttons">        
        <a class="btn btn-contens-delete" id="delete-yes" href="javascript:void(0)">はい</a>
        <a class="btn btn-contens-delete" href="javascript:void(0)" onclick="hidePopup('deleteComfirmPopup');">いいえ</a>
    </div>
</div>

<div class="row">
    <div class="col-sm-12" style="margin-top: 10px;">
        <table id="listId" class="table table-striped table-bordered table-hover table-common">
            <thead>
                <tr>
                    <th class="text-center">ユーザーID</th>
                    <th class="text-center">企業・団体名</th>
                    <th class="text-center">担当者氏名</th>
                    <th class="text-center">オーナー名</th>
                    <th class="text-center">削除</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                    foreach ($this->data as $row) :
                ?>
                <tr>
                    <td class="text-center"><a href="<?= $this->url('user', array('action' => 'update', 'id' => $row['user_id'])); ?>"><?= $row['user_id'];?></a></td>
                    <td class="text-left"><?= isset($row['organization']) ? $row['organization'] : null; ?></td>
                    <td class="text-left"><?= isset($row['contact']) ? $row['contact'] : null; ?></td>
                    <td class="text-left"><?= isset($row['user_name']) ? $row['user_name'] : null; ?></td>
                    <td class="text-center">
                        <a class="btn btn-contens-delete" uid="<?= $row['user_id'] ?>" href="javascript:void(0)" onclick="onDeleteUserClick(this);">削除</a>
                    </td>
                </tr>
                <?php endforeach; ?>                              
                                
            </tbody>
        </table>
    </div>
</div>

<div id="listId_paginator" class="row"> 
    <?php echo $this->paginationControl($this->paginator,
                                        'Sliding',
                                        'paginator-slide', array(
                                                            'route' => 'user',
                                                            'action' => 'paging',
                                                            'tableId' => 'listId',
                                                            'order_by' => $this->order_by,
                                                            'order' => $this->order,
                                                            'addParamCallback' => 'paging',
            )); ?>
</div>

<br/>

<ul class="nav nav-tabs" id="UserFilterTabBar">
    <li key="1" class="active"><a href="javascript:void(0)" onclick="userFilterTab(1)">チャネルオーナー</a></li>
    <li key="2"><a href="javascript:void(0)" onclick="userFilterTab(2)">正規コンテンツオーナー</a></li>
    <li key="3"><a href="javascript:void(0)" onclick="userFilterTab(3)">一般ユーザー</a></li>
    <li key="4"><a href="javascript:void(0)" onclick="userFilterTab(4)" style="margin-right: 0px;">登録申請中ユーザー</a></li>
</ul>

<script>
    $(document).ready(function () {
        lastPage = 1;
        lastOrderBy = 'name';
        lastOrder = 'ASC';
    });
    
    function paging(params) {        
        params.tab = $('#UserFilterTabBar > li[class=active]').attr('key');
    }
</script>