<?php
$this->headScript()->appendFile($this->basePath() . '/js/channel.js');

$appHelper = $this->ApplicationHelper();
$titleName = $appHelper->getHeadTitle('Omolink\Channel\Update');
$this->headTitle($titleName);

$form = $this->form;
$form->setAttribute('action', $this->url('channel', array('action' => 'update', 'id' => $this->channelId)));
$form->setAttribute('enctype','multipart/form-data');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<!--Hiển thị tiêu đề của trang web-->
<div class="bs-callout bs-callout-info">
    <h4 class="title-text-bold"><?php echo $this->escapeHtml($titleName); ?>
    </h4>
</div>

<?php
if (isset($this->successMessage)) :
    ?>
    <div class="alert alert-info" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <?= $this->translate($this->successMessage) ?>
    </div>
<?php endif; ?>

<?php if (isset($this->errorMessage)) : ?>
    <div class="alert alert-danger" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <?= $this->translate($this->errorMessage) ?>
    </div>
<?php endif; ?>

<?php
echo $this->form()->openTag($form);
echo $this->formRow($form->get('csrf'));
?>

<div id="registerComfirmPopup" class="overlay-content" style="width:250px;height:120px">
    <div class="popup-title"><?php echo $this->escapeHtml($titleName); ?></div>
    <div class="popup-content">入力された情報を更新しますか？</div>
    <div class="popup-buttons">        
        <a class="btn btn-contens-delete" href="javascript:void(0)" onclick="showLoading();registerSubmit();">はい</a>
        <a class="btn btn-contens-delete" href="javascript:void(0)" onclick="hidePopup('registerComfirmPopup');">いいえ</a>
    </div>
</div>

<div>（<img src="/img/notered.png">）マークは必須項目です。</div>
<div class="row" id="inputContainer">
    <div class="form-horizontal">
        <div class="col-sm-12">
            <table class="table table-bordered table-hover table-title  tblChannel">
                <tr>
                    <td class="require"><span>チャネル名</span></td>
                    <td>
                        <div class="col-sm-6 col-sm-trim-pading">
                            <?= $this->formRow($form->get('channelName')); ?>                            
                        </div>
                    </td>
                </tr>
                <tr>
                    <td class="require"><span>チャネル説明</span></td>
                    <td>
                        <div class="col-sm-12 col-sm-trim-pading">
                            <?= $this->formRow($form->get('channelDescription')); ?>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>バナー画像</td>
                    <td>
                        <div class="col-sm-6 col-sm-trim-pading">
                            <?= $this->formFile($form->get('fileBannerImgPhoto')); ?>
                            <?= $this->formRow($form->get('txtBannerImage')); ?>
                        </div>
                        <div class="col-sm-4">
                               <a class="btn btn-default btn-up-img" onclick="onBannerImgClick()">参照</a>                       
                        </div>
                        <div class="col-sm-6 col-sm-trim-pading content-top img-format">
                              <img src="<?= isset($this->channelData['bannerImage']) && !is_null($this->channelData['bannerImage']) ? $this->channelData['bannerImage'] : '/img/no_image.jpg' ;?>" class="img-thumbnail" id="bannerImage">                  
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>コンテンツフレーム上画像</td>
                    <td>
                        <div class="col-sm-6 col-sm-trim-pading">
                            <?= $this->formFile($form->get('fileFrameOnImagePhoto')); ?>
                            <?= $this->formRow($form->get('txtFrameOnImage')); ?>
                        </div>
                        <div class="col-sm-4">
                               <a class="btn btn-default btn-up-img" onclick="onFrameOnImgClick()">参照</a>                       
                        </div>
                        <div class="col-sm-6 col-sm-trim-pading content-top img-format">
                              <img src="<?= isset($this->channelData['frameOnImage']) && !is_null($this->channelData['frameOnImage']) ? $this->channelData['frameOnImage'] : '/img/no_image.jpg' ;?>" class="img-thumbnail" id="frameOnImage">                  
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>コンテンツフレーム下画像</td>
                    <td>
                        <div class="col-sm-6 col-sm-trim-pading">
                            <?= $this->formFile($form->get('fileFrameUnderImagePhoto')); ?>
                            <?= $this->formRow($form->get('txtFrameUnderImage')); ?>
                        </div>
                        <div class="col-sm-4">
                               <a class="btn btn-default btn-up-img" onclick="onFrameUnderImgClick()">参照</a>                       
                        </div>
                        <div class="col-sm-6 col-sm-trim-pading content-top img-format">
                              <img src="<?= isset($this->channelData['frameUnderImage']) && !is_null($this->channelData['frameUnderImage']) ? $this->channelData['frameUnderImage'] : '/img/no_image.jpg' ;?>" class="img-thumbnail" id="frameUnderImage">                  
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>コンテンツアイコン画像</td>
                    <td>
                        <div class="col-sm-6 col-sm-trim-pading">
                            <?= $this->formFile($form->get('fileFrameIconImagePhoto')); ?>
                            <?= $this->formRow($form->get('txtIconImage')); ?>
                        </div>
                        <div class="col-sm-4">
                               <a class="btn btn-default btn-up-img" onclick="onFrameIconImgClick()">参照</a>                       
                        </div>
                        <div class="col-sm-6 col-sm-trim-pading content-top img-format">
                              <img src="<?= isset($this->channelData['frameIconImage']) && !is_null($this->channelData['frameIconImage']) ? $this->channelData['frameIconImage'] : '/img/no_image.jpg' ;?>" class="img-thumbnail" id="frameIconImage">                  
                        </div>
                    </td>
                </tr>

            </table>

        </div>        
    </div>
</div>
<?= $this->formRow($form->get('channelId')); ?>
<div class="form-group">
    <div class="col-sm-12 text-center">
        <div class="btn-wrapper">
            <?= $this->formRow($form->get('btnRegister')->setAttribute('value', '更新')
                                                        ->setOptions(array('label' => '更新'))
            );?>
        </div>
    </div>
</div>

<?= $this->form()->closeTag(); ?>


