<!--<script type="text/javascript">
    $(document).ready(function () {
        $("#login_submit").bind('click', function (event) {
            $("#login").submit();
        });
    });
</script>-->

<?php
//:::: Head title
$appHelper = $this->ApplicationHelper();
$this->headTitle($appHelper->getHeadTitle('Application\Login\LoginView'));

$form = $this->loginFrm;
$form->setAttribute('action', $this->url(null, array('controller' => 'login', 'action' => 'loginView')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<div class="row login">
    <div class="text-right login-container">
        <?= $this->form()->openTag($form) ?>
        <?php 
            if (!Empty($this->errorMessage)):
        ?>
            <div class="col-sm-10 text-left login-error">
                <span class="lable-login"><?php echo (isset($this->errorMessage)) ? $this->translate($this->errorMessage) : ''; ?></span>
            </div>
        <?php endif; ?>
        
        <div class="form-group">
            <div class="col-sm-11" style="margin-top: 20px; padding-left: 45px">
                <?=
                    $this->formRow($form->get('login_name')
                            ->setAttribute('class', 'form-control'))
                ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-11" style="padding-top: 5px; padding-left: 45px">
                <?=
                    $this->formRow($form->get('login_password')
                            ->setAttribute('class', 'form-control'))
                ?>
            </div>
        </div>
        </br>
        
        <div class="form-group">
            <div class="col-sm-12 text-center">
                <div class="btn-wrapper">
                    <?= $this->formRow($form->get('btnLogin')); ?>
            </div>
        </div>
</div>

<!--        <div class="form-group">
            <div class="col-sm-12 text-center" style="padding-bottom: 10px; ">
                <a href="javascript:void(0)" class="btn btn-lg btn-primary btn-size" id="login_submit">
                    <i class="ic-login"></i>ログイン
                </a>
            </div>
        </div>-->
                    
        </div> 
                <div class="form-group">
                <div class="col-sm-12 text-center label-new-register">
                    <span>オーナー未登録の方</span>
                </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12 text-center">
                <a class="btn btn-lg btn-new-register" href="<?= $this->url('user', array('action' => 'insert')) ;?>">新規登録</a>
            </div>
        </div>

    <?= $this->form()->closeTag() ?>

</div>

<script>
    if (typeof(Storage) !== "undefined") {
         sessionStorage.setItem("prevLinks", '');
    }
</script>