<?php echo $this->doctype(); ?>

<html lang="jp">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('｜おもりんく管理')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this
            ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '#'))
            ->prependStylesheet(array('rel' => 'icon', 'href' => $this->basePath() .'/img/login_favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/style-layout.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
            ->prependStylesheet($this->basePath() . '/css/datepicker3.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/main.js') 
            ->prependFile($this->basePath() . '/js/paging.js')
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/locales/bootstrap-datepicker.ja.js')
            ->prependFile($this->basePath() . '/js/bootstrap-datepicker.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

        <!--Custom scripts-->
        <script type="text/javascript">
            $(document).ready(function () {
                $('.dropdown-toggle').dropdown();
            });
        </script>
    </head>
    <body class="body-layout">
        <div id="overlay" class="overlay">
        </div>
        <!--Header content-->
        <div id="headerNav" class="container-fluid">
            <div class="col-sm-2 nav-right">
                <div class="text-right">
                    <img src="<?= $this->basePath() . '/img/logo.png' ?>" style="height: 35px;"/>
                </div>
            </div>
        </div>

        <!--Main content-->
        <div class="container-fluid">
            <div class="container-center">
                <?php
                    echo $this->content;
                ?>
            </div>
            <!--<hr>-->
        </div>
        <br/>
        <br/>
        <br/>
        <br/>
        <div class="footer">
            <div class="text-right layout-footer">おもりんく管理 Version</div>
        </div>
    </body>
</html>
