<?php
//:::: Head title
$appHelper = $this->ApplicationHelper();
$this->headTitle($appHelper->getHeadTitle('Application\Password\ChangePassword'));

//:::: Form
$form = $this->passwordForm;
$form->setAttribute('action', $this->url(null, array('controller' => 'password', 'action' => 'changePassword')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('csrf'));
?>
<h1>パスワード変更</h1>
<?php if (isset($this->messageInfo)) : ?>
    <div class="alert alert-info" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <?= $this->translate($this->messageInfo); ?>
    </div>
<?php endif; ?>

<div class="row" id="inputContainer">
    <div class="form-horizontal">
        <div class="col-md-12">
            <div class="form-group">
                <label class="col-md-3 control-label" for="loginName">現在のパスワード<span class="required">*</span></label>
                <div class="col-md-3">
                    <?= $this->formRow($form->get('oldPassword')) ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label" for="loginName">新パスワードの入力<span class="required">*</span></label>
                <div class="col-md-3">
                    <?= $this->formRow($form->get('newPassword')) ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label" for="loginName">新パスワードの確認<span class="required">*</span></label>
                <div class="col-md-3">
                    <?= $this->formRow($form->get('confirmPassword')) ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <div class="btn-wrapper">
                        <?= $this->formSubmit($form->get('updateBtn')) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>
