<div class="text-center">
    <h2>おもりんく管理</h2>
</div>
<?php
//:::: Head title
$appHelper = $this->ApplicationHelper();
$this->headTitle($appHelper->getHeadTitle('Application\Password\PasswordSetting'));

//:::: Form
$form = $this->form;
$form->setAttribute('action', $this->url('password', array('action' => 'password_setting'), array('query' => array('hashKey' => $this->hashKey))
));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('csrf'));
?>

<div id="inputContainer" class="row">
    <div class="form-horizontal">
        <h1>パスワード再設定</h1>

        <?php if (isset($this->error_HashKey)) { ?>
            <?= $this->translate($this->error_HashKey); ?>
        <?php } else if ($this->isSuccess) { ?>
            <p>
                パスワード再設定が完了しました。
            </p>
            <p>
                <a href="<?= $this->url('home') ?>">ログイン画面</a>でログインしてください。
            </p>
        <?php } else { ?>

            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-3 control-label">事業所ID<span class="required">*</span></label>
                    <div class="col-md-3">
                        <?= $this->formRow($form->get('facilityId')) ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">新しいパスワード<span class="required">*</span></label>
                    <div class="col-md-3">
                        <?= $this->formRow($form->get('newPassword')) ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">パスワード確認<span class="required">*</span></label>
                    <div class="col-md-3">
                        <?= $this->formRow($form->get('confirmPassword')) ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="btn-wrapper">
                            <?= $this->formSubmit($form->get('btnUpdate')) ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<?= $this->form()->closeTag() ?>
