<div class="text-center">
    <h2>おもりんく管理</h2>
    <h3>パスワードリセット</h3>
    <h5>事業所IDを入力してください。パスワード変更画面へのリンクを記載したメールを送信します。</h5>
    <h5>（この機能はメールアカウントを登録している事業所のみ使用できます）</h5>
</div>
<?php
$appHelper = $this->ApplicationHelper();
$this->headTitle($appHelper->getHeadTitle('Application\Password\PasswordReset'));

$form = $this->form;
$form->setAttribute('action', $this->url('password', array('action' => 'password_reset')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<div class="row">
    <div class="position-pass-setting">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <div class="col-sm-9">
                <?= $this->formRow($form->get('csrf')); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-9">

                <?=
                $this->formRow($form->get('pass_facilityId')
                        ->setAttribute('class', 'form-control'))
                ?>
            </div>
            <div class="col-sm-1 col-sm-trim-pading">
                <?=
                $this->formRow($form->get('pass_submit')
                        ->setAttribute('class', 'btn btn-primary'))
                ?>
            </div>

        </div>
        <?= $this->form()->closeTag() ?>
        <?php if (isset($this->messageInfo)) : ?>
            <div class="col-sm-9 alert alert-info text-left" role="alert">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <?= $this->translate($this->messageInfo); ?>
            </div>
        <?php endif; ?>
        <?php if (isset($this->messageError)) : ?>
            <div class="col-sm-9 alert alert-danger text-left" role="alert">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <?= $this->translate($this->messageError); ?>
            </div>
        <?php endif; ?>
    </div>
</div>

